name: Heroku Deployment

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Cambia según la versión de Node.js que uses

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        git push heroku HEAD:main --force

    - name: Verify deployment
      run: |
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com)
        if [ $RESPONSE -ne 200 ]; then
          echo "Deployment failed"
          exit 1
        else
          echo "Deployment succeeded"
        fi
