name: Heroku Deployment

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        git push heroku HEAD:main
